apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azure-vote.fullname" . }}-secret
  labels:
    {{- include "azure-vote.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ .Values.redis.password | toString | b64enc | quote }}
